/**
 * lib/services/pdv-lead-router.service.ts
 * ---------------------------------------------------------------------------
 * Intelligent Lead Router -- QR Code PDV Interception
 * ---------------------------------------------------------------------------
 *
 * RESPONSIBILITY:
 *   Intercept WhatsApp messages containing a PDV tracking tag,
 *   create the Lead with correct origin (QR_CODE_PDV), link to the
 *   manager-promotor of that PDV, and inject a personalized System Prompt
 *   for the AI greeting.
 *
 * FULL FLOW:
 *   1. Webhook receives customer message
 *   2. extractPdvTag(text) detects tag "[Ref: PDV-<id>]" via Regex
 *   3. If found -> routeQrCodeLead() is called before generic flow
 *   4. routeQrCodeLead():
 *      a. Finds PartnerStore by extracted pdvId
 *      b. Creates or updates Lead with sourceType = QR_CODE_PDV
 *      c. Links Lead to PDV and managerPromoter (PDV owner)
 *      d. Increments totalLeads counter on PDV
 *      e. Creates CommissionLedger PENDING for manager-promotor (network commission)
 *      f. Creates AlertLog to notify promotor in mobile app
 *   5. buildPdvSystemPrompt() generates personalized System Prompt:
 *      - PDV name, city, store type
 *      - Manager-promotor name (VIP consultant)
 *      - Instructions: thank the PDV capture and collect vehicle data
 *   6. dispatchPdvIaGreeting() sends AI greeting with personalized prompt
 *
 * TRACKING TAG FORMAT:
 *   Inserted in the QR Code URL generated by the system:
 *     https://wa.me/55{PHONE}?text=Ola!%20[Ref%3A%20PDV-{pdvId}]
 *
 *   Examples of messages containing the tag:
 *     "Ola! [Ref: PDV-cmmgdem5e00018clnvyufpvja]"
 *     "oi tenho interesse [Ref: PDV-abc123]"
 *     "[Ref: PDV-xyz789] quero saber mais"
 *
 * REGEX:
 *   /\[Ref:\s*PDV-([a-zA-Z0-9_-]+)\]/i
 *   Captures everything between "PDV-" and "]"
 *   Compatible with cuid(), nanoid(), UUID
 *
 * ANTI-DUPLICATE SAFETY:
 *   Upsert by (telefoneNorm + pdvId): if customer already exists as a lead
 *   for that PDV, only updates status and does NOT duplicate CommissionLedger.
 */

import { prisma } from '@/lib/prisma'

// ---------------------------------------------------------------------------
// SAFRA (Cohort) helper
// ---------------------------------------------------------------------------

/**
 * Computes the "safra" (crop/batch) label for a lead based on its creation date.
 *
 * The safra groups leads by the month/year they entered the system,
 * allowing campaign managers to target a batch without repeating contacts.
 *
 * Format: "MM/YYYY"   e.g. "03/2026"
 *
 * @param date   Date of lead creation (defaults to now)
 * @returns      Safra string like "03/2026"
 *
 * @example
 * computeSafra()              // -> "03/2026"   (if current month is March 2026)
 * computeSafra(new Date('2026-01-15'))  // -> "01/2026"
 */
export function computeSafra(date: Date = new Date()): string {
  const month = String(date.getMonth() + 1).padStart(2, '0')  // 01..12
  const year  = String(date.getFullYear())                      // 2026
  return `${month}/${year}`
}

/**
 * Returns a human-readable label for the safra.
 * Used in UI badges and campaign labels.
 *
 * @example
 * safraLabel("03/2026")  // -> "Safra Mar/26"
 * safraLabel("12/2025")  // -> "Safra Dez/25"
 */
export function safraLabel(cohort: string): string {
  const [mm, yyyy] = cohort.split('/')
  const monthNames = ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
  const monthName  = monthNames[parseInt(mm, 10) - 1] ?? mm
  const shortYear  = yyyy.slice(-2)
  return `Safra ${monthName}/${shortYear}`
}

/**
 * Parses a safra string into a Date range (start/end of that month).
 * Useful for date-range queries in analytics and campaign scheduling.
 *
 * @example
 * safraToDates("03/2026")
 * // -> { start: 2026-03-01T00:00:00Z, end: 2026-03-31T23:59:59Z }
 */
export function safraToDates(cohort: string): { start: Date; end: Date } {
  const [mm, yyyy] = cohort.split('/')
  const month = parseInt(mm, 10) - 1
  const year  = parseInt(yyyy, 10)
  const start = new Date(year, month, 1, 0, 0, 0, 0)
  const end   = new Date(year, month + 1, 0, 23, 59, 59, 999)  // last day of month
  return { start, end }
}

// ---------------------------------------------------------------------------
// PDV tag extraction regex
//
// Tag format: [Ref: PDV-{pdvId}]
// Valid examples:
//   [Ref: PDV-cmmgdem5e00018clnvyufpvja]
//   [Ref:PDV-abc123]
//   [ref: pdv-XYZ789]  (case-insensitive)
//
const PDV_TAG_REGEX = /\[Ref:\s*PDV-([a-zA-Z0-9_-]+)\]/i

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PdvRouteContext {
  /** PDV ID extracted from tag */
  pdvId: string
  /** PDV name (e.g. "Posto Ipiranga Centro") */
  pdvName: string
  /** PDV city */
  pdvCidade: string | null
  /** Store type (e.g. "POSTO_COMBUSTIVEL") */
  storeType: string
  /** Manager-promotor ID (who receives network commission) */
  promotorId: string | null
  /** Manager-promotor name */
  promotorNome: string | null
  /** ID of created/updated Lead */
  leadId: string
  /** Personalized System Prompt for AI greeting */
  systemPrompt: string
  /** true = new lead, false = existing lead updated */
  isNewLead: boolean
}

export interface PdvTagExtraction {
  found: boolean
  pdvId?: string
  /** Message text without the tracking tag (clean text to save in DB) */
  cleanText: string
}

// ---------------------------------------------------------------------------
// 1. TAG EXTRACTOR
// ---------------------------------------------------------------------------

/**
 * Checks if the message contains the [Ref: PDV-{id}] tag and extracts pdvId.
 *
 * @param text   Raw content of msg.text.body
 * @returns      { found, pdvId, cleanText }
 *
 * @example
 * extractPdvTag("Ola! [Ref: PDV-abc123]")
 * // -> { found: true, pdvId: "abc123", cleanText: "Ola!" }
 *
 * extractPdvTag("Quero um rastreador")
 * // -> { found: false, cleanText: "Quero um rastreador" }
 */
export function extractPdvTag(text: string): PdvTagExtraction {
  const match = PDV_TAG_REGEX.exec(text)

  if (!match) {
    return { found: false, cleanText: text.trim() }
  }

  const pdvId     = match[1]                          // group 1: captured ID
  const cleanText = text.replace(PDV_TAG_REGEX, '')   // remove tag from text
                        .replace(/\s{2,}/g, ' ')      // normalize double spaces
                        .trim()

  return { found: true, pdvId, cleanText }
}

// ---------------------------------------------------------------------------
// 2. MAIN ROUTER
// ---------------------------------------------------------------------------

/**
 * Executes the full routing flow when a PDV tag is detected.
 *
 * @param pdvId         PDV ID extracted from tag
 * @param from          Customer phone number (E.164 without +)
 * @param contactName   Contact name (from Meta payload)
 * @param tenantId      Tenant ID (obtained via Channel)
 * @param cleanText     Clean message text (without tag)
 * @returns             PdvRouteContext with all data for AI greeting
 */
export async function routeQrCodeLead(
  pdvId:       string,
  from:        string,
  contactName: string,
  tenantId:    string,
  cleanText:   string,
): Promise<PdvRouteContext | null> {

  // 2a. Find PDV in database
  const pdv = await prisma.partnerStore.findFirst({
    where: {
      id:      pdvId,
      tenantId,
      status:  'ACTIVE',
    },
    include: {
      managerPromoter: {
        select: { id: true, nome: true, email: true, tenantId: true },
      },
    },
  })

  if (!pdv) {
    console.warn(
      `[PdvRouter] PDV ID "${pdvId}" not found or inactive for tenant ${tenantId}.`,
      'Message routed to generic flow.',
    )
    return null   // falls through to generic webhook flow
  }

  console.log(
    `[PdvRouter] QR Code lead detected! PDV: "${pdv.name}" | Customer: ${from}`,
  )

  // 2b. Normalize phone number (remove Brazilian 55 prefix)
  const telefoneNorm = from.replace(/^55/, '')

  // 2c. Upsert Lead (create if not exists for this PDV + phone combination)
  //
  // Strategy: search for existing lead by (telefoneNorm + pdvId).
  // If exists (customer scanned again): update iaStatus only.
  // If not exists: create new lead with all links.
  //
  const existingLead = await prisma.lead.findFirst({
    where: {
      telefoneNorm,
      pdvId,
      tenantId,
    },
    orderBy: { createdAt: 'desc' },
  })

  let lead: { id: string }
  let isNewLead = false

  if (existingLead) {
    // Lead already exists -> update AI status only
    lead = await prisma.lead.update({
      where: { id: existingLead.id },
      data: {
        iaStatus:    'RECONTATADO',
        funnelStage: existingLead.funnelStage === 'LEAD_COLETADO'
          ? 'IA_EM_ATENDIMENTO'
          : existingLead.funnelStage,
        updatedAt:   new Date(),
      },
      select: { id: true },
    })

    console.log(`[PdvRouter] Existing lead updated: ${lead.id}`)
  } else {
    // New lead -> full creation with all links
    lead = await prisma.lead.create({
      data: {
        // Customer data
        nomeCliente:   contactName,
        telefone:      `+${from}`,
        telefoneNorm,

        // QR Code PDV origin
        sourceType:    'QR_CODE_PDV',
        pdvId:         pdv.id,
        promotorId:    pdv.managerPromoterId,   // promotor managing the PDV

        // ── Safra automática ─────────────────────────────────────────────────
        // Groups this lead into a monthly cohort for campaign targeting.
        // Prevents duplicate mass sends to the same customer in the same period.
        // Format: "MM/YYYY" — computed from entry date (now).
        //
        cohort:        computeSafra(),           // e.g. "03/2026"

        // Initial stage
        funnelStage:   'IA_EM_ATENDIMENTO',
        iaStatus:      'CONTATADO',
        status:        'PENDENTE_AUDITORIA',

        // Multi-tenant
        tenantId,
      },
      select: { id: true },
    })

    isNewLead = true
    console.log(`[PdvRouter] New QR Code Lead created: ${lead.id}`)

    // 2d. Increment totalLeads counter on PDV
    await prisma.partnerStore.update({
      where: { id: pdv.id },
      data:  { totalLeads: { increment: 1 } },
    }).catch(e => console.warn('[PdvRouter] Failed to increment totalLeads:', e))

    // 2e. CommissionLedger PENDING for manager-promotor
    //
    // Creates a PENDING entry in the promotor's network commission ledger.
    // Will become "PAID" when the lead converts to a sale (via sale.service.ts).
    // Ensures traceability: the PDV installation credit is attributed to the
    // promotor who placed the QR Code, even without an immediate sale.
    //
    if (pdv.managerPromoterId) {
      await prisma.commissionLedger.create({
        data: {
          promotorId:     pdv.managerPromoterId,
          leadId:         lead.id,
          commissionType: 'QR_CODE_CAPTURE',
          pdvId:          pdv.id,
          eventType:      'QR_CODE_PDV_LEAD',
          amount:         0,                    // calculated when sale closes
          description:    `QR Code lead captured -- ${pdv.name} | ${contactName} (${telefoneNorm})`,
          status:         'PENDING',
          tenantId,
        },
      }).catch(e => console.warn('[PdvRouter] Failed to create CommissionLedger:', e))

      // 2f. AlertLog to notify promotor in mobile app
      await prisma.alertLog.create({
        data: {
          tenantId,
          subjectUserId: pdv.managerPromoterId,
          type:          'NEW_QR_CODE_LEAD',
          title:         'New lead via QR Code!',
          message:
            `${contactName} scanned the QR Code at ${pdv.name} ` +
            `and made contact via WhatsApp. AI is already handling it.`,
          severity: 'INFO',
          metadata: JSON.stringify({
            leadId:    lead.id,
            pdvId:     pdv.id,
            pdvName:   pdv.name,
            telefone:  telefoneNorm,
            contactName,
          }),
        },
      }).catch(e => console.warn('[PdvRouter] Failed to create AlertLog:', e))
    }
  }

  // 2g. Build and return full context
  const systemPrompt = buildPdvSystemPrompt({
    pdvName:      pdv.name,
    pdvCidade:    pdv.cidade,
    storeType:    pdv.storeType,
    promotorNome: pdv.managerPromoter?.nome ?? null,
    contactName,
    isNewLead,
    cleanText,
  })

  return {
    pdvId:        pdv.id,
    pdvName:      pdv.name,
    pdvCidade:    pdv.cidade,
    storeType:    pdv.storeType,
    promotorId:   pdv.managerPromoterId,
    promotorNome: pdv.managerPromoter?.nome ?? null,
    leadId:       lead.id,
    systemPrompt,
    isNewLead,
  }
}

// ---------------------------------------------------------------------------
// 3. PERSONALIZED SYSTEM PROMPT BUILDER
// ---------------------------------------------------------------------------

interface PdvPromptOptions {
  pdvName:      string
  pdvCidade:    string | null
  storeType:    string
  promotorNome: string | null
  contactName:  string
  isNewLead:    boolean
  cleanText:    string
}

/**
 * Generates the AI System Prompt adjusted to the PDV context.
 * Injects PDV name, city, store type, and sales instructions.
 */
export function buildPdvSystemPrompt(opts: PdvPromptOptions): string {
  const {
    pdvName, pdvCidade, storeType, promotorNome,
    contactName, isNewLead, cleanText,
  } = opts

  const storeLabel = STORE_TYPE_LABELS[storeType] ?? 'partner establishment'
  const localDesc  = pdvCidade ? `${pdvName} in ${pdvCidade}` : pdvName
  const promotorMention = promotorNome
    ? ` (managed by consultant ${promotorNome})`
    : ''

  const greetingSection = isNewLead
    ? `The customer ${contactName} just made contact by scanning the QR Code `
    + `at the partner ${storeLabel} "${localDesc}"${promotorMention}. `
    + (cleanText ? `Their initial message was: "${cleanText}". ` : '')
    + `This is the FIRST interaction of this customer with our company.`
    : `Customer ${contactName} returned by scanning the QR Code again `
    + `at ${storeLabel} "${localDesc}". Treat them as a lead who already knows our company.`

  return `You are a high-performance Vehicle Telemetry and Tracking Solutions Consultant.
You represent the company and are attending a lead from a passive QR Code capture.

--- CAPTURE CONTEXT ---
${greetingSection}

--- YOUR ROLE IN THIS ATTENDANCE ---
Act as a VIP consultant specialized in telemetry solutions for fleets.
Your mission is:
  1. Thank the interest generated by the partner "${pdvName}" in a natural and warm way
  2. Ask about the customer's vehicle (license plate, model, usage: personal/fleet)
  3. Identify the main pain point (security, fleet control, fuel savings)
  4. Briefly present our most suitable solution for the profile
  5. Advance to a diagnosis or commercial proposal

--- TONE AND STYLE ---
- Be warm, professional, and straight to the point
- Use consultative language (not telemarketing)
- Maximum 3 lines per message (WhatsApp has quick reading)
- Use emojis with moderation (1-2 per message)
- Never mention that you are an AI; act as a human consultant

--- FIRST MESSAGE (mandatory) ---
ALWAYS start by thanking the visit to "${pdvName}" and asking about the vehicle.
Opening example:
"Hello, ${contactName}! Great that you stopped by ${pdvName}!
To help you in the best way, tell me: what is your vehicle? (plate or model)"

--- CRITICAL RULES ---
- NEVER invent prices without confirming the catalog
- If customer asks for human: inform that a consultant will contact them within 2h
- TOTAL FOCUS on collecting: vehicle, plate, main need`
}

// Store type to human-readable label mapping
const STORE_TYPE_LABELS: Record<string, string> = {
  POSTO_COMBUSTIVEL:  'gas station',
  LOJA_VAREJO:        'retail partner store',
  OFICINA:            'partner garage',
  TRANSPORTADORA:     'partner carrier',
  OUTROS:             'partner establishment',
}

// ---------------------------------------------------------------------------
// 4. AI GREETING DISPATCHER
// ---------------------------------------------------------------------------

/**
 * Sends the initial AI greeting with the PDV-personalized System Prompt.
 *
 * Complete implementation:
 *  1. Fetch conversation history (normally empty for new leads)
 *  2. Build OpenAI payload with PDV systemPrompt
 *  3. Call openai.chat.completions.create(...)
 *  4. Save response as Message { senderType: 'BOT' }
 *  5. Send via WhatsApp API
 *
 * @param conversationId   Conversation ID (created/existing)
 * @param to               Customer phone number (E.164 without +)
 * @param tenantId         Tenant ID
 * @param context          PDV context (contains systemPrompt)
 */
export async function dispatchPdvIaGreeting(
  conversationId: string,
  to:             string,
  tenantId:       string,
  context:        PdvRouteContext,
): Promise<void> {
  const openaiKey = process.env.OPENAI_API_KEY
  if (!openaiKey) {
    console.warn('[PdvRouter] OPENAI_API_KEY not configured -- AI greeting not sent.')
    return
  }

  try {
    // 4a. Call OpenAI with PDV-personalized System Prompt
    const aiResponse = await callOpenAI({
      systemPrompt:     context.systemPrompt,
      userFirstMessage: '',           // first message = system prompt only
      model:            'gpt-4o-mini',
      apiKey:           openaiKey,
    })

    if (!aiResponse) {
      console.error('[PdvRouter] OpenAI returned empty response.')
      return
    }

    // 4b. Save AI response in DB as BOT message
    await prisma.message.create({
      data: {
        conversationId,
        senderType: 'BOT',
        senderName: 'IA Consultora',
        content:    aiResponse,
        messageType: 'text',
      },
    })

    // 4c. Send via WhatsApp API
    const { sendTextMessage } = await import('./whatsapp.service')
    const result = await sendTextMessage(to, aiResponse, tenantId)

    if (result.success) {
      console.log(
        `[PdvRouter] AI greeting sent to ${to} | PDV: "${context.pdvName}" | wamid: ${result.waMessageId}`,
      )
    } else {
      console.error(`[PdvRouter] Failed to send AI greeting: ${result.error}`)
    }

    // 4d. Update conversation with PDV lead context tag
    //     Uses buyingIntent field to store the QR Code origin for inbox filters
    await prisma.conversation.update({
      where: { id: conversationId },
      data: {
        buyingIntent: `QR_CODE_PDV | pdv:${context.pdvId} | lead:${context.leadId}`,
        updatedAt:    new Date(),
      },
    }).catch(() => void 0)  // non-critical -- do not block

  } catch (err) {
    console.error('[PdvRouter] Error dispatching AI greeting:', err)
  }
}

// ---------------------------------------------------------------------------
// 5. MINIMAL OPENAI CLIENT
//
// Direct fetch implementation to keep service dependency-free.
// In projects that already have openai installed, replace with:
//   const openai = new OpenAI({ apiKey })
//   const res = await openai.chat.completions.create({...})
// ---------------------------------------------------------------------------

interface OpenAICallOpts {
  systemPrompt:      string
  userFirstMessage:  string
  model:             string
  apiKey:            string
}

async function callOpenAI(opts: OpenAICallOpts): Promise<string | null> {
  const { systemPrompt, userFirstMessage, model, apiKey } = opts

  const messages: { role: string; content: string }[] = [
    { role: 'system', content: systemPrompt },
  ]

  // Include user's first message in history if present
  if (userFirstMessage.trim()) {
    messages.push({ role: 'user', content: userFirstMessage })
  }

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method:  'POST',
    headers: {
      'Content-Type':  'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages,
      max_tokens:   300,
      temperature:  0.7,
    }),
  })

  if (!res.ok) {
    const err = await res.text()
    throw new Error(`OpenAI HTTP ${res.status}: ${err.slice(0, 200)}`)
  }

  const data = await res.json() as {
    choices: Array<{ message: { content: string } }>
  }

  return data.choices?.[0]?.message?.content?.trim() ?? null
}
